apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs
spec:
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteMany
  nfs:
    # FIXME: use the right IP
    path: /exports
    server: 172.31.0.100
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-myapp
spec:
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteMany
  nfs:
    # FIXME: use the right IP
    path: /myapp
    server: 172.31.0.100
