apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: helloworld
  name: helloworld-svc
spec:
  ports:
  - port: 80
    nodePort: 31001
    protocol: TCP
    targetPort: 80
  selector:
    app: helloworld
  type: NodePort
status:
  loadBalancer: {}
